steps:
# build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/demo-pipeline:$COMMIT_SHA', '-t', 'gcr.io/$PROJECT_ID/demo-pipeline:latest','.']
# push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/demo-pipeline:$COMMIT_SHA']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/demo-pipeline:latest']
- name: 'gcr.io/cloud-builders/kubectl'
  args: ['apply', '-f', 'k8s/*']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-c'
  - 'CLOUDSDK_CONTAINER_CLUSTER=spinnaker'
# Upload k8s manifest to gcs
artifacts:
  objects:
    location: 'gs://demo-pipeline-1/'
    paths: ['k8s/*.yml']
images:
- 'gcr.io/$PROJECT_ID/demo-pipeline:$COMMIT_SHA'
- 'gcr.io/$PROJECT_ID/demo-pipeline:latest'