apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: demo-pipeline
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: demo-pipeline
    spec:
      containers:
      - name: demo-pipeline
        image: gcr.io/testnubity/demo-pipeline
        resources:
          limits:
            memory: "500Mi"
            cpu: "100m"
        imagePullPolicy: Always