apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-pipeline
spec:
  replicas: 3
  selector:
    matchLabels:
      app: demo-pipeline
  template:
    metadata:
      labels:
        app: demo-pipeline
    spec:
      containers:
      - name: demo-pipeline
        image: gcr.io/sistemas-portal-servicios-cicd/demo-pipeline
        resources:
          limits:
            memory: "500Mi"
            cpu: "100m"
        imagePullPolicy: Always
