apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: abargon-test
spec:
  replicas: 2
  template:
    metadata:
      labels:
        editor: vscode
    spec:
      containers:
      - name: abargon
        image: gcr.io/testnubity/abargon-test
        resources:
          limits:
            memory: "500Mi"
            cpu: "100m"
        imagePullPolicy: Always