apiVersion: v1
kind: Service
metadata:
  labels:
    app: abargon-test
  name: abargon-test
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: abargon-test
  sessionAffinity: None
  type: ClusterIP